### ISSUE TITLE
Server Down

### ISSUE THREAD

**Issue by DakshCodess** [uros-5/ui-lishuuro#2]
The server is down i guess so see this image - 
![Opera Snapshot_2023-03-04_153636_lishuuro org](https://user-images.githubusercontent.com/97610126/222893925-205bbe8c-80fb-411b-ac7a-7099c4e4fb35.png)

**Comment by uros-5** [comment]
It will be up very soon.

**Comment by DakshCodess** [comment]
Thank You @uros-5 , I am also learning Programming Core python from today onwards . Till my web development , I wanna help you with ur project i'm intrested in .
