### ISSUE TITLE
New Chess Board

### ISSUE THREAD

**Issue by DakshCodess** [uros-5/ui-lishuuro#3]
12 X 12 new board issue @uros-5 
![IMG_20230305_100108](https://user-images.githubusercontent.com/97610126/222955183-b63972af-a2ac-4a3a-8a21-6bca8669601a.jpg)

**Comment by uros-5** [comment]
This is not 12x12 board. And it's not SVG file.

**Comment by DakshCodess** [comment]
Sorry @uros-5 i m curious to help you , i will upload an SVG file chess board image
